language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install .
  - pip install coveralls
# command to run tests
script:
  coverage run --source=yarn_api_client /usr/bin/env python2.7 setup.py test
after_success:
  coveralls
