language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install pip coveralls
# command to run tests
script:
  tox
env:
  - TOXENV=py26
  - TOXENV=py27
after_success:
  coveralls
